import React from 'react'
import SideBar from '../../components/Sidebar'

export const metadata = {
  title: "My | Dashboard",
  description: "Generated by lex developers",
};
function layout({children}) {
  return (
    <div className='flex h-screen md:flex-row flex-col md:overflow-hidden flex-grow'>


<div className='md:w-64  h-0 flex-none w-full '> <SideBar/></div>
      
      
      
      <div className=' w-full  flex-grow md:overflow-y-auto  md:p-6 ' >{children}</div>
    </div>
  )
}

export default layout
